### ISSUE TITLE
target_namespace var is returning a boolean and some other namespace stuff

### ISSUE THREAD

**Issue by madorn** [opdev/opcap-ansible#35]
In #34, noticed that `target_namespace` will return a boolean if we don't close up the input parameter.

https://github.com/opdev/opcap-ansible/blob/0ff04f1079f2a0e313da49895452decb7b1bd32f/install.yml#L81

Changing to following worked for me:
`target_namespace: "{{ (item in ['OwnNamespace']) | ternary(full_namespace, [full_namespace, 'targetns1'] | join('-')) }}"`

Another quick thing:

When it comes time to install an Operator in `AllNamespaces` mode (if AllNamespaces == true), where do we want to put the CR?

`openshift-operators`?

Wherever we end up dropping the CR, can we set `target_namespace` var with that namespace name when installing Operator in AllNamespaces mode, i.e.

```
target_namespace: "openshift-operators"
when: item in ['AllNamespaces']
```

For reasons mentioned in #32 , thinking we can remove lookups and references to MultiNamespace InstallMode:
https://github.com/opdev/opcap-ansible/blob/0ff04f1079f2a0e313da49895452decb7b1bd32f/install.yml#L25

**Comment by bcrochet** [comment]
> In #34, noticed that `target_namespace` will return a boolean if we don't close up the input parameter.
> 
> https://github.com/opdev/opcap-ansible/blob/0ff04f1079f2a0e313da49895452decb7b1bd32f/install.yml#L81
> 
> Changing to following worked for me: `target_namespace: "{{ (item in ['OwnNamespace']) | ternary(full_namespace, [full_namespace, 'targetns1'] | join('-')) }}"`

Kinda strange. It seemed to work for me. So could be a jinja'ism that I didn't account for.

> 
> Another quick thing:
> 
> When it comes time to install an Operator in `AllNamespaces` mode (if AllNamespaces == true), where do we want to put the CR?
> 
> `openshift-operators`?
> 
> Wherever we end up dropping the CR, can we set `target_namespace` var with that namespace name when installing Operator in AllNamespaces mode, i.e.
> 
> ```
> target_namespace: "openshift-operators"
> when: item in ['AllNamespaces']
> ```
> 
> For reasons mentioned in #32 , thinking we can remove lookups and references to MultiNamespace InstallMode:
> 
> https://github.com/opdev/opcap-ansible/blob/0ff04f1079f2a0e313da49895452decb7b1bd32f/install.yml#L25

AllNamespaces should have just ended up in the "targetns1" namespace. That's the point of the ternary. If it isn't OwnNamespace, it should go in targetns1. Which is why I based it on that. I'll take a look at why it's doing that boolean thing that you witnessed in the AM.

**Comment by madorn** [comment]
>> AllNamespaces should have just ended up in the "targetns1" namespace. That's the point of the ternary. If it isn't OwnNamespace, it should go in targetns1. Which is why I based it on that. I'll take a look at why it's doing that boolean thing that you witnessed in the AM.

When we run in AllNamespaces, we run `Create main namespace` task called `opcap-<packagename>-allnamespaces` but we skip all `Create additional namespace` tasks.

Like you mentioned, although `target_namespace` ends up declared with `opcap-<packagename>-allnamespaces-targetns1` when the ternary isn't OwnNamespace, that namespace won't exist on CR creation.

Thanks!
